Fix load order of angular-perfect-scrollbar vs angular which was leading to the link() function being invoked to early:
Error: $elem.perfectScrollbar is not a function
.link@http://localhost:9000/scripts-requirejs/vendor/angular-perfect-scrollbar.js:26:7
nodeLinkFn@http://localhost:9000/bower_components/angular/angular.js:6580:1
compositeLinkFn@http://localhost:9000/bower_components/angular/angular.js:5983:1
nodeLinkFn@http://localhost:9000/bower_components/angular/angular.js:6573:9
...